# Generated by Django 2.2.24 on 2021-09-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
